extends Node

const Fixtures := preload(
	"res://tests/helpers/map_runtime_transaction_test_fixtures.gd"
)
const BuildService := preload(
	"res://scripts/map_editor/map_editor_build_runtime_service.gd"
)
const Bridge := preload(
	"res://scripts/layers/runtime/map_editor_runtime_bridge.gd"
)
const Mapper := preload("res://scripts/map_coordinate_mapper.gd")

const MAP_KEY := "future_test_map"
const MAP_ID := 990123
const REG_PATH := "user://p0_3r_future_registry.json"


func _ready() -> void:
	_run.call_deferred()


func _run() -> void:
	Fixtures.reset_seams()
	var formal_root := (
		"user://p0_3r_formal/future_%d/" % Time.get_ticks_usec()
	)
	BuildService.test_formal_runtime_root_override = formal_root
	# Start from an EMPTY registry: no pre-seeded entry for the future map.
	Fixtures.write_registry(REG_PATH, [])
	Bridge.test_override_release_registry_path(REG_PATH)
	assert(not Bridge.is_formal_playable(MAP_ID))
	assert(Bridge.released_map_ids().is_empty())
	# Build Candidate (content only) does not create any formal release.
	var doc := Fixtures.make_document(MAP_KEY, MAP_ID, "Future Map")
	var approval := BuildService.approve_for_runtime(doc)
	assert(approval.ok, str(approval.get("errors", [])))
	var candidate := BuildService.build_candidate(doc)
	assert(candidate.ok, str(candidate.get("errors", [])))
	var hash := str(candidate.build_sha256)
	assert(
		str(candidate.candidate_path).begins_with(
			"res://outputs/map_runtime_candidates/"
		)
	)
	assert(
		not Bridge.is_formal_playable(MAP_ID),
		"candidate alone must not grant playability"
	)
	var formal_path := BuildService.default_runtime_path(MAP_KEY)
	assert(
		not FileAccess.file_exists(formal_path),
		"formal runtime must not exist before publish"
	)
	# Publish: registry new entry + formal runtime generated by the transaction.
	var published := BuildService.publish_runtime_release(
		str(candidate.candidate_path), MAP_ID, REG_PATH
	)
	assert(bool(published.get("success", false)), str(published))
	assert(bool(published.get("formal_playable", false)))
	assert(FileAccess.file_exists(formal_path))
	var reg: Dictionary = Fixtures.read_json(REG_PATH)
	assert(reg.maps.size() == 1)
	assert(int(reg.maps[0].runtime_map_id) == MAP_ID)
	assert(str(reg.maps[0].map_key) == MAP_KEY)
	assert(str(reg.maps[0].runtime_path) == formal_path)
	assert(str(reg.maps[0].approved_build_sha256) == hash)
	assert(int(reg.maps[0].approval_revision) == 1)
	# Bridge dynamically recognizes the new map without any code edit.
	assert(Bridge.is_formal_playable(MAP_ID))
	assert(str(Bridge.load_map(MAP_ID).get("build_sha256", "")) == hash)
	var profile: Dictionary = Mapper.resolve_formal_runtime_projection_profile(
		MAP_ID
	)
	assert(bool(profile.get("success", false)))
	assert(
		str(profile.get("policy", ""))
		== str(Mapper.PROJECTION_POLICY_MAP_EDITOR_RUNTIME_ABSOLUTE)
	)
	# Simulated restart: still playable from registry + formal artifact.
	Bridge.reset_release_registry_override()
	Bridge.test_override_release_registry_path(REG_PATH)
	assert(Bridge.is_formal_playable(MAP_ID))
	assert(str(Bridge.load_map(MAP_ID).get("build_sha256", "")) == hash)
	Fixtures.reset_seams()
	print("FUTURE_MAP_BUILD_PUBLISH_NO_CODE_EDIT_PASS")
	get_tree().quit(0)
