extends Node


func _ready() -> void:
	var document := MapEditorTypes.new_map("stage4_instance_test", 991004, "Stage4 Instance Test", Vector2i(64, 64))
	var campfire := MapEditorInstanceService.create_instance(document, "mse.small_decor.001", "decoration", Vector2i(8, 8))
	assert(campfire.ok, str(campfire.get("errors", [])))
	assert(campfire.instance.object_role == "decoration" and campfire.instance.scene_intent == "visual_detail")
	assert(campfire.instance.collision_policy == "none" and campfire.instance.content_layer == "personal_expansion")
	var tent := MapEditorInstanceService.create_instance(document, "mse.small_decor.002", "building", Vector2i(20, 20))
	assert(tent.ok, str(tent.get("errors", [])))
	assert(Vector2i(int(tent.instance.footprint_tiles[0]), int(tent.instance.footprint_tiles[1])) == Vector2i(6, 6))
	assert(tent.instance.collision_policy == "none" and tent.instance.collision_footprint_tiles == [0, 0])
	assert(tent.instance.placement_rule == "inside_map")
	var overlap := MapEditorInstanceService.create_instance(document, "mse.small_decor.003", "building", Vector2i(21, 20))
	assert(overlap.ok, str(overlap.get("errors", [])))
	assert(overlap.instance.placement_rule == "inside_map")
	var moved := MapEditorInstanceService.move_instance(document, str(tent.instance.instance_id), Vector2i(21, 20))
	assert(moved.ok and moved.instance.tile == [21, 20])
	var chest := MapEditorInstanceService.create_instance(document, "mse.small_decor.004", "interactable", Vector2i(20, 20))
	assert(chest.ok and chest.instance.gameplay_role == "interactable")
	var chest_located := MapEditorInstanceService._locate(document, str(chest.instance.instance_id))
	chest_located.instance["scale"] = [0.75, 0.75]
	chest_located.instance["offset_px"] = [7, -5]
	chest_located.instance["instance_custom_scale"] = true
	MapEditorInstanceService._located_replace(document, chest_located, chest_located.instance)
	var duplicate := MapEditorInstanceService.duplicate_instance(document, str(chest.instance.instance_id), Vector2i(21, 20))
	assert(duplicate.ok)
	assert(str(duplicate.instance.instance_id) != str(chest.instance.instance_id))
	assert(duplicate.instance.tile == [21, 20] and duplicate.instance.tile_anchor == [21, 20])
	assert(duplicate.instance.scale == [0.75, 0.75])
	assert(duplicate.instance.offset_px == [7, -5])
	assert(bool(duplicate.instance.instance_custom_scale))
	var deleted := MapEditorInstanceService.delete_instance(document, str(duplicate.instance.instance_id))
	assert(deleted.ok)
	assert(MapEditorInstanceService.all_instances(document).size() == 4)
	var path := "user://mse_stage4_instance_%s.editor.json" % Time.get_ticks_usec()
	var saved := MapEditorSaveService.save_document(document, path)
	assert(saved.ok, str(saved.get("errors", [])))
	var loaded := MapEditorLoadService.load_document(path)
	assert(loaded.ok and MapEditorInstanceService.all_instances(loaded.document).size() == 4)
	print("MSE_STAGE4_INSTANCE_SEMANTICS_PASS")
	get_tree().quit(0)
