extends Node

const GroundUnitSpaceScript := preload("res://scripts/ground_unit_space.gd")


func _ready() -> void:
	var document := MapEditorTypes.new_map("stage7_runtime", 990007, "Stage 7", Vector2i(32, 32))
	document.editor_meta.workspace = "user://mse_stage7_runtime_%s" % str(Time.get_ticks_usec())
	var ground := MapEditorGroundService.initialize(document)
	assert(ground.ok)
	var npc := MapEditorGameplaySemanticService.add_entry(document, "npc", Vector2i(3, 3), {"content_id": "npc.bich_guard", "npc_id": "npc.bich_guard"})
	var door := MapEditorGameplaySemanticService.add_entry(document, "door", Vector2i(4, 4), {"target_map_id": "bich_province", "target_tile": [8, 8]})
	var entrance := MapEditorGameplaySemanticService.add_entry(document, "map_entrance", Vector2i(5, 5), {"display_name": "测试入口"})
	var map_exit := MapEditorGameplaySemanticService.add_entry(document, "map_exit", Vector2i(6, 5), {"target_map_id": "bich_province", "target_entrance_id": str(entrance.entry.semantic_id)})
	var respawn := MapEditorGameplaySemanticService.add_entry(document, "respawn_point", Vector2i(7, 7), {"display_name": "出生复活点"})
	var safe_polygon := MapEditorGameplaySemanticService.add_entry(document, "safe_area", Vector2i(7, 7), {
		"shape": "polygon", "polygon_ground_gu": [[5, 5], [9, 5], [9, 9], [5, 9]], "radius_gu": 0.0,
	})
	var wall := MapEditorInstanceService.create_instance(document, "terrain.palisade_wall_01", "terrain", Vector2i(10, 10), "terrain_base")
	assert(npc.ok and door.ok and entrance.ok and map_exit.ok and respawn.ok and safe_polygon.ok and wall.ok)
	var no_approval := MapEditorBuildRuntimeService.build(document, "user://stage7_runtime.runtime.json")
	assert(not no_approval.ok)
	assert("runtime_approval_required" in no_approval.errors)
	var approval := MapEditorBuildRuntimeService.approve_for_runtime(document)
	assert(approval.ok, str(approval.get("errors", [])))
	var built := MapEditorBuildRuntimeService.build(document, "user://stage7_runtime.runtime.json")
	assert(built.ok, str(built.get("errors", [])))
	assert(built.runtime.collision.blocked_count == 3)
	assert(built.runtime.semantics.npc_points.size() == 1)
	assert(built.runtime.semantics.door_points[0].target_map_id == "bich_province")
	assert(built.runtime.semantics.map_entrance_points.size() == 1)
	assert(built.runtime.semantics.map_exit_points[0].target_entrance_id == str(entrance.entry.semantic_id))
	assert(built.runtime.semantics.respawn_points[0].is_birth_point)
	assert(built.runtime.runtime_schema_version == MapEditorBuildRuntimeService.RUNTIME_SCHEMA_VERSION)
	assert(built.runtime.unit_contract_id == GroundUnitSpaceScript.CONTRACT_ID)
	assert(built.runtime.projection_contract_id == GroundUnitSpaceScript.PROJECTION_CONTRACT_ID)
	assert(built.runtime.semantics.safe_area[0].polygon_ground_gu.size() == 4)
	assert(not built.runtime.semantics.safe_area[0].has("polygon_tiles"))
	assert(not built.runtime.semantics.safe_area[0].has("radius_tiles"))
	assert(is_zero_approx(float(built.runtime.semantics.safe_area[0].radius_gu)))
	var runtime_errors := MapEditorRuntimeMapService.validate_runtime(built.runtime)
	assert(runtime_errors.is_empty(), str(runtime_errors))
	var wrong_contract: Dictionary = built.runtime.duplicate(true)
	wrong_contract["unit_contract_id"] = "wrong"
	assert("runtime_unit_contract_invalid" in MapEditorRuntimeMapService.validate_runtime(wrong_contract))
	var legacy_field: Dictionary = built.runtime.duplicate(true)
	legacy_field.semantics.safe_area[0]["radius_tiles"] = 0.0
	assert(
		"runtime_legacy_radius_forbidden:%s" % str(safe_polygon.entry.semantic_id)
		in MapEditorRuntimeMapService.validate_runtime(legacy_field)
	)
	assert(not MapEditorJsonCodec.encode(built.runtime).contains("map_editor_workspace"))
	var paint := MapEditorGroundService.record_tile_paint(document, Vector2i(1, 1), "ground.dark_grass.001")
	assert(paint.ok)
	var dirty_build := MapEditorBuildRuntimeService.build(document, "user://stage7_runtime_dirty.runtime.json")
	assert(not dirty_build.ok)
	assert("ground_dirty_chunks_must_be_baked" in dirty_build.errors)
	var bake := MapEditorChunkBakeService.bake_dirty_chunks(document)
	assert(bake.ok, str(bake.get("errors", [])))
	var rebuilt := MapEditorBuildRuntimeService.build(document, "user://stage7_runtime_baked.runtime.json")
	assert(rebuilt.ok, str(rebuilt.get("errors", [])))
	print("MSE_STAGE7_BUILD_RUNTIME_PASS")
	get_tree().quit()
