extends Node


func _ready() -> void:
	var document := MapEditorTypes.new_map("stage7_runtime", 990007, "Stage 7", Vector2i(32, 32))
	document.editor_meta.workspace = "user://mse_stage7_runtime_%s" % str(Time.get_ticks_usec())
	var ground := MapEditorGroundService.initialize(document)
	assert(ground.ok)
	var npc := MapEditorGameplaySemanticService.add_entry(document, "npc", Vector2i(3, 3), {"content_id": "npc.bich_guard", "npc_id": "npc.bich_guard"})
	var door := MapEditorGameplaySemanticService.add_entry(document, "door", Vector2i(4, 4), {"target_map_id": "bich_province", "target_tile": [8, 8]})
	var wall := MapEditorInstanceService.create_instance(document, "terrain.palisade_wall_01", "terrain", Vector2i(10, 10), "terrain_base")
	assert(npc.ok and door.ok and wall.ok)
	var no_approval := MapEditorBuildRuntimeService.build(document, "user://stage7_runtime.runtime.json")
	assert(not no_approval.ok)
	assert("runtime_approval_required" in no_approval.errors)
	var approval := MapEditorBuildRuntimeService.approve_for_runtime(document)
	assert(approval.ok, str(approval.get("errors", [])))
	var built := MapEditorBuildRuntimeService.build(document, "user://stage7_runtime.runtime.json")
	assert(built.ok, str(built.get("errors", [])))
	assert(built.runtime.collision.blocked_count == 3)
	assert(built.runtime.semantics.npc_points.size() == 1)
	assert(built.runtime.semantics.door_points[0].target_map_id == "bich_province")
	assert(not MapEditorJsonCodec.encode(built.runtime).contains("map_editor_workspace"))
	var paint := MapEditorGroundService.record_tile_paint(document, Vector2i(1, 1), "ground.dark_grass.001")
	assert(paint.ok)
	var dirty_build := MapEditorBuildRuntimeService.build(document, "user://stage7_runtime_dirty.runtime.json")
	assert(not dirty_build.ok)
	assert("ground_dirty_chunks_must_be_baked" in dirty_build.errors)
	var bake := MapEditorChunkBakeService.bake_dirty_chunks(document)
	assert(bake.ok, str(bake.get("errors", [])))
	var rebuilt := MapEditorBuildRuntimeService.build(document, "user://stage7_runtime_baked.runtime.json")
	assert(rebuilt.ok, str(rebuilt.get("errors", [])))
	print("MSE_STAGE7_BUILD_RUNTIME_PASS")
	get_tree().quit()
