extends Node


func _ready() -> void:
	var document := MapEditorTypes.new_map("stage6_semantics", 990006, "Stage 6", Vector2i(64, 64))
	var npc := MapEditorGameplaySemanticService.add_entry(document, "npc", Vector2i(4, 5), {"content_id": "npc.bich_guard", "npc_id": "npc.bich_guard"})
	assert(npc.ok)
	assert(npc.entry.service_role == "dialogue")
	var spawn := MapEditorGameplaySemanticService.add_entry(document, "monster_spawn", Vector2i(10, 10), {"content_id": "monster.strawman", "monster_id": "monster.strawman", "radius_tiles": 4})
	assert(spawn.ok)
	assert(spawn.entry.respawn_seconds == 60)
	var boss := MapEditorGameplaySemanticService.add_entry(document, "boss_spawn", Vector2i(20, 20), {"content_id": "boss.skeleton_elite", "boss_id": "boss.skeleton_elite"})
	assert(boss.ok)
	assert(boss.entry.respawn_seconds == 1800)
	var invalid_door := MapEditorGameplaySemanticService.add_entry(document, "door", Vector2i(1, 1))
	assert(not invalid_door.ok)
	assert("door_target_map_required" in invalid_door.errors)
	var door := MapEditorGameplaySemanticService.add_entry(document, "door", Vector2i(2, 2), {"target_map_id": "bich_province", "target_tile": [33, 40]})
	assert(door.ok)
	var safe := MapEditorGameplaySemanticService.add_entry(document, "safe_area", Vector2i(5, 5), {"radius_tiles": 6})
	var light := MapEditorGameplaySemanticService.add_entry(document, "light", Vector2i(6, 6), {"radius_tiles": 3, "flicker": true})
	var trigger := MapEditorGameplaySemanticService.add_entry(document, "region_trigger", Vector2i(7, 7), {"radius_tiles": 2, "action": "enter_bich_gate"})
	assert(safe.ok and light.ok and trigger.ok)
	assert(MapEditorGameplaySemanticService.all_entries(document).size() == 7)
	var path := "user://mse_stage6_semantics_%s.editor.json" % Time.get_ticks_usec()
	var saved := MapEditorSaveService.save_document(document, path)
	assert(saved.ok, str(saved.get("errors", [])))
	var loaded := MapEditorLoadService.load_document(path)
	assert(loaded.ok, str(loaded.get("errors", [])))
	assert(MapEditorGameplaySemanticService.all_entries(loaded.document).size() == 7)
	print("MSE_STAGE6_GAMEPLAY_SEMANTICS_PASS")
	get_tree().quit()
