extends Node


func _ready() -> void:
	var document := MapEditorTypes.new_map("stage4_instance_test", 991004, "Stage4 Instance Test", Vector2i(64, 64))
	var campfire := MapEditorInstanceService.create_instance(document, "prop.campfire_stone_01", "decoration", Vector2i(8, 8))
	assert(campfire.ok, str(campfire.get("errors", [])))
	assert(campfire.instance.object_role == "decoration" and campfire.instance.scene_intent == "visual_detail")
	assert(campfire.instance.collision_policy == "none" and campfire.instance.content_layer == "personal_expansion")
	var tent := MapEditorInstanceService.create_instance(document, "building.gothic_tent_01", "building", Vector2i(20, 20))
	assert(tent.ok, str(tent.get("errors", [])))
	assert(Vector2i(int(tent.instance.footprint_tiles[0]), int(tent.instance.footprint_tiles[1])) == Vector2i(3, 2) and tent.instance.collision_policy == "solid_footprint")
	var overlap := MapEditorInstanceService.create_instance(document, "building.blacksmith_forge_01", "building", Vector2i(21, 20))
	assert(not overlap.ok and str(overlap.errors[0]).begins_with("blocked_footprint_overlap"))
	var moved := MapEditorInstanceService.move_instance(document, str(tent.instance.instance_id), Vector2i(30, 20))
	assert(moved.ok and moved.instance.tile == [30, 20])
	var chest := MapEditorInstanceService.create_instance(document, "prop.storage_chest_01", "interactable", Vector2i(20, 20))
	assert(chest.ok and chest.instance.gameplay_role == "interactable")
	var duplicate := MapEditorInstanceService.duplicate_instance(document, str(chest.instance.instance_id), Vector2i(21, 20))
	assert(duplicate.ok)
	var deleted := MapEditorInstanceService.delete_instance(document, str(duplicate.instance.instance_id))
	assert(deleted.ok)
	assert(MapEditorInstanceService.all_instances(document).size() == 3)
	var path := "user://mse_stage4_instance_%s.editor.json" % Time.get_ticks_usec()
	var saved := MapEditorSaveService.save_document(document, path)
	assert(saved.ok, str(saved.get("errors", [])))
	var loaded := MapEditorLoadService.load_document(path)
	assert(loaded.ok and MapEditorInstanceService.all_instances(loaded.document).size() == 3)
	print("MSE_STAGE4_INSTANCE_SEMANTICS_PASS")
	get_tree().quit(0)
