#!/usr/bin/env python
import os
from SCons.Script import SConscript, Default, ARGUMENTS

sdk = os.path.abspath(os.path.join(os.getcwd(), '..', '..', '..', 'outputs', 'native_kernel_sdk', 'godot-cpp'))
if ARGUMENTS.get('api_version') != '4.7':
    raise RuntimeError('api_version=4.7 is required')
env = SConscript(os.path.join(sdk, 'SConstruct'), exports={'api_version': '4.7'})
env.Append(CPPPATH=['src'])
src = ['src/crowd_melee_kernel.cpp', 'src/register_types.cpp']
target = os.path.join('bin', 'crowd_melee_kernel.windows.template_debug.x86_64.dll')
Default(env.SharedLibrary(target, src))
