# Generated by tools/build_hud_target_bar_mask.py; edit the source contract.
extends RefCounted
const SOURCE_SHA256 := "e595460b66850d568a193410fff9a67d0d56d14718ea7721a5b9108af3edceaf"
const SOURCE_SIZE := Vector2(660, 109)
const INNER_BOUNDS := Rect2i(99, 33, 464, 39)
const INNER_PIXEL_COUNT := 17121
