"""Import six fixed 2x4 transparent sheets as one deterministic decoration pack.

Each source is a fixed 1448x1086 RGBA canvas.  The source contract is a
two-row by four-column grid (362x543 cells); every cell is cropped to its
alpha>=8 tight bounding box, copied byte-for-byte as RGBA, and surrounded by
eight transparent pixels.  The importer writes only its independent catalog
and the 48 owned PNGs, so it cannot append or replace the main asset catalog.

``--check`` is read-only and rebuilds all expected bytes in memory.
``--write`` is deterministic and refuses a catalog owned by another pack.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from io import BytesIO
from pathlib import Path
from typing import Any

import numpy as np
from PIL import Image


ROOT = Path(__file__).resolve().parents[2]
CATALOG_PATH = ROOT / "assets/data/assets/map_small_decoration_asset_catalog.json"
OUTPUT_ROOT = ROOT / "assets/art/maps/_shared/user_palette/decorations_1/small_decorations_20260822"
PALETTE_PATH = "装饰物1/小装饰物"
PACKAGE_ID = "mse_small_decoration_pack_20260822_v1"
PIPELINE = "alpha_grid_tight_bbox_rgba_preserve_v1"
ALPHA_THRESHOLD = 8
PADDING_PX = 8
GRID_ROWS = 2
GRID_COLUMNS = 4
CELL_SIZE = (362, 543)
CANVAS_SIZE = (1448, 1086)
TILE_SIZE = [64, 32]
FOOTPRINT_UNIT_PX = 64

SOURCE_SPECS: tuple[dict[str, Any], ...] = (
    {
        "path": Path(r"C:\Users\Administrator\Downloads\ChatGPT Image 2026年8月22日 00_23_20 (1).png"),
        "sha256": "8be80c66724d336181e9bc8079ffad44d9c9551de890d2efc022c52fdd4c85bb",
    },
    {
        "path": Path(r"C:\Users\Administrator\Downloads\ChatGPT Image 2026年8月22日 00_23_21 (2).png"),
        "sha256": "f1bf8692cc5e2bf0d0170d2a4fb846252bfb3bd4bc77b6242aea7aa7d0b5985d",
    },
    {
        "path": Path(r"C:\Users\Administrator\Downloads\ChatGPT Image 2026年8月22日 00_23_22 (6).png"),
        "sha256": "5aac9e5b20d0a6ff44987e21e1878b8809194a03971520bbaf5398db513d7171",
    },
    {
        "path": Path(r"C:\Users\Administrator\Downloads\ChatGPT Image 2026年8月22日 00_23_23 (7).png"),
        "sha256": "53cd858b9573acafd383569dbba0b7444ba2664469a14e83d015d2336e2ac10c",
    },
    {
        "path": Path(r"C:\Users\Administrator\Downloads\ChatGPT Image 2026年8月22日 00_23_23 (8).png"),
        "sha256": "b1fc6bd2692934a9316bcc527dba537430f4f9e731215737b0ae69b65924243b",
    },
    {
        "path": Path(r"C:\Users\Administrator\Downloads\ChatGPT Image 2026年8月22日 00_23_25 (10).png"),
        "sha256": "372e74f329b3ccfeb6bca3d2c2cb7582ebad535b6d07779e233a97a15caba58e",
    },
)


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def png_bytes(image: Image.Image) -> bytes:
    buffer = BytesIO()
    # Explicit encoder options keep generated bytes stable across runs.
    image.save(buffer, format="PNG", optimize=False, compress_level=9)
    return buffer.getvalue()


def read_source(spec: dict[str, Any]) -> tuple[Image.Image, str]:
    path = Path(spec["path"])
    if not path.is_file():
        raise ValueError(f"missing source: {path}")
    payload = path.read_bytes()
    actual_sha = sha256_bytes(payload)
    if actual_sha != str(spec["sha256"]):
        raise ValueError(
            f"source SHA mismatch: {path}\n"
            f"expected={spec['sha256']} actual={actual_sha}"
        )
    with Image.open(BytesIO(payload)) as opened:
        opened.load()
        if opened.mode != "RGBA":
            raise ValueError(f"{path}: expected RGBA, got {opened.mode}")
        image = opened.copy()
    if tuple(image.size) != CANVAS_SIZE:
        raise ValueError(f"{path}: expected {CANVAS_SIZE}, got {image.size}")
    return image, actual_sha


def alpha_bbox(image: Image.Image) -> tuple[int, int, int, int]:
    alpha = np.asarray(image.getchannel("A"), dtype=np.uint8)
    ys, xs = np.where(alpha >= ALPHA_THRESHOLD)
    if len(xs) == 0:
        raise ValueError("grid cell has no alpha>=8 pixels")
    x1 = int(xs.min())
    y1 = int(ys.min())
    x2 = int(xs.max()) + 1
    y2 = int(ys.max()) + 1
    return x1, y1, x2, y2


def cut_cell(source: Image.Image, row: int, column: int) -> tuple[Image.Image, dict[str, Any]]:
    cell_x = column * CELL_SIZE[0]
    cell_y = row * CELL_SIZE[1]
    cell = source.crop((cell_x, cell_y, cell_x + CELL_SIZE[0], cell_y + CELL_SIZE[1]))
    x1, y1, x2, y2 = alpha_bbox(cell)
    cropped = cell.crop((x1, y1, x2, y2))
    output = Image.new(
        "RGBA",
        (cropped.width + PADDING_PX * 2, cropped.height + PADDING_PX * 2),
        (0, 0, 0, 0),
    )
    output.paste(cropped, (PADDING_PX, PADDING_PX))
    visible_bounds = [PADDING_PX, PADDING_PX, cropped.width, cropped.height]
    inner = np.asarray(output)[PADDING_PX:PADDING_PX + cropped.height, PADDING_PX:PADDING_PX + cropped.width]
    if not np.array_equal(inner, np.asarray(cropped)):
        raise ValueError(f"RGBA pixels changed during copy row={row + 1} column={column + 1}")
    alpha = np.asarray(output.getchannel("A"), dtype=np.uint8)
    visible_mask = np.zeros_like(alpha, dtype=bool)
    vx, vy, vw, vh = visible_bounds
    visible_mask[vy:vy + vh, vx:vx + vw] = True
    if bool(np.any((alpha >= ALPHA_THRESHOLD) & ~visible_mask)):
        raise ValueError(f"alpha escaped crop row={row + 1} column={column + 1}")
    source_bounds = [cell_x + x1, cell_y + y1, x2 - x1, y2 - y1]
    return output, {
        "cell_bounds_px": [cell_x, cell_y, CELL_SIZE[0], CELL_SIZE[1]],
        "cell_row": row + 1,
        "cell_column": column + 1,
        "cell_alpha_bbox_px": [x1, y1, x2 - x1, y2 - y1],
        "source_bounds_px": source_bounds,
        "visible_bounds_px": visible_bounds,
        "visible_alpha_pixel_count": int(np.count_nonzero(alpha >= ALPHA_THRESHOLD)),
        "output_size": list(output.size),
    }


def build_expected() -> tuple[dict[str, Any], dict[str, bytes]]:
    assets: list[dict[str, Any]] = []
    outputs: dict[str, bytes] = {}
    source_records: list[dict[str, Any]] = []
    stable_index = 0
    for source_index, spec in enumerate(SOURCE_SPECS, start=1):
        source, source_sha = read_source(spec)
        source_records.append({
            "source_index": source_index,
            "source_external_path": str(spec["path"]),
            "source_sha256": source_sha,
            "source_canvas": list(CANVAS_SIZE),
            "grid": [GRID_ROWS, GRID_COLUMNS],
            "cell_size_px": list(CELL_SIZE),
            "alpha_threshold": ALPHA_THRESHOLD,
        })
        for row in range(GRID_ROWS):
            for column in range(GRID_COLUMNS):
                stable_index += 1
                output, geometry = cut_cell(source, row, column)
                image_rel = (
                    Path("assets/art/maps/_shared/user_palette/decorations_1/small_decorations_20260822")
                    / f"small_decoration_{stable_index:03d}.png"
                ).as_posix()
                output_payload = png_bytes(output)
                outputs[image_rel] = output_payload
                visible = geometry["visible_bounds_px"]
                visible_width = int(visible[2])
                visible_height = int(visible[3])
                footprint = [
                    (visible_width + FOOTPRINT_UNIT_PX - 1) // FOOTPRINT_UNIT_PX,
                    (visible_height + FOOTPRINT_UNIT_PX - 1) // FOOTPRINT_UNIT_PX,
                ]
                anchor = [
                    int(visible[0]) + visible_width // 2,
                    int(visible[1]) + visible_height - 1,
                ]
                processing = {
                    "pipeline": PIPELINE,
                    "grid": [GRID_ROWS, GRID_COLUMNS],
                    "cell_size_px": list(CELL_SIZE),
                    "grid_row": row + 1,
                    "grid_column": column + 1,
                    "alpha_threshold": ALPHA_THRESHOLD,
                    "padding_px": PADDING_PX,
                    "cell_alpha_bbox_px": geometry["cell_alpha_bbox_px"],
                    "source_bounds_px": geometry["source_bounds_px"],
                    "rgba_pixels_preserved": True,
                    "footprint_estimation": "visible_bounds_ceil_div_64_pending_manual",
                    "output_mask_edge_touch": [],
                }
                assets.append({
                    "asset_id": f"mse.small_decor.{stable_index:03d}",
                    "display_name": f"小装饰物 {stable_index:03d}",
                    "asset_type": "small_prop",
                    "category": "visual_detail",
                    "object_class": "decoration",
                    "theme": "user_palette",
                    "image": image_rel,
                    "thumbnail": image_rel,
                    "canvas_size": list(output.size),
                    "image_size": list(output.size),
                    "visible_bounds_px": visible,
                    "selection_bounds_px": visible.copy(),
                    "anchor_px": anchor,
                    "placement_anchor_px": anchor.copy(),
                    "anchor_tile": [0, 0],
                    "anchor_mode": "foot_tile",
                    "footprint_tiles": footprint.copy(),
                    "visual_footprint_tiles": footprint.copy(),
                    "occupancy_footprint_tiles": footprint.copy(),
                    "base_footprint_tiles": footprint.copy(),
                    "collision_footprint_tiles": [0, 0],
                    "collision_cells": [],
                    "placement_clearance_cells": [],
                    "tile_size": TILE_SIZE.copy(),
                    "approved_scale": 1.0,
                    "logical_scale_level": 0,
                    "scale_approved": False,
                    "anchor_approved": False,
                    "default_layer": "object_base",
                    "default_object_role": "decoration",
                    "semantic_role": "visual_detail",
                    "collision_policy": "none",
                    "collision_profile_id": "none_visual",
                    "navigation_policy": "ignore",
                    "manual_collision_expected": True,
                    "map_collision_override": "default",
                    "collision_authority": "manual_by_user",
                    "occlusion": False,
                    "content_layer": "personal_expansion",
                    "placeable": True,
                    "calibration_status": "placeable",
                    "calibration_source": "pending_manual_geometry_v1",
                    "geometry_pending_manual": True,
                    "palette_path": PALETTE_PATH,
                    "source_external_path": str(spec["path"]),
                    "source_sha256": source_sha,
                    "source_canvas": list(CANVAS_SIZE),
                    "source_grid": [row + 1, column + 1],
                    "source_cell_bounds_px": geometry["cell_bounds_px"],
                    "source_bounds_px": geometry["source_bounds_px"],
                    "source_alpha_bbox_px": geometry["cell_alpha_bbox_px"],
                    "output_sha256": sha256_bytes(output_payload),
                    "thumbnail_source_sha256": sha256_bytes(output_payload),
                    "processing": processing,
                    "tags": [
                        "new_local_asset",
                        "small_decoration",
                        "visual_detail",
                        "decoration",
                        PIPELINE,
                    ],
                    "editable": True,
                    "allows_edge_clipping": True,
                    "trigger_on_enter": False,
                    "package_id": PACKAGE_ID,
                    "source_index": source_index,
                    "source_grid_row": row + 1,
                    "source_grid_column": column + 1,
                    "projection": "orthographic_isometric_2_to_1",
                })
    catalog = {
        "asset_schema_version": 2,
        "package_id": PACKAGE_ID,
        "package_version": 1,
        "classification": PALETTE_PATH,
        "palette_path": PALETTE_PATH,
        "source_count": len(SOURCE_SPECS),
        "asset_count": len(assets),
        "grid": [GRID_ROWS, GRID_COLUMNS],
        "cell_size_px": list(CELL_SIZE),
        "cutting_policy": PIPELINE,
        "alpha_threshold": ALPHA_THRESHOLD,
        "padding_px": PADDING_PX,
        "default_collision_policy": "none",
        "default_collision_profile_id": "none_visual",
        "default_navigation_policy": "ignore",
        "collision_authority": "manual_by_user",
        "geometry_pending_manual": True,
        "sources": source_records,
        "assets": assets,
    }
    if len(assets) != 48 or len(outputs) != 48:
        raise AssertionError(f"expected 48 assets and outputs, got {len(assets)} / {len(outputs)}")
    return catalog, outputs


def read_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"JSON root must be an object: {path}")
    return value


def write_json(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def validate_existing(
    catalog: dict[str, Any], expected: dict[str, Any], outputs: dict[str, bytes]
) -> list[str]:
    errors: list[str] = []
    expected_assets = expected["assets"]
    actual_assets = catalog.get("assets", [])
    if catalog.get("package_id") != PACKAGE_ID:
        errors.append("catalog.package_id_mismatch")
    if catalog.get("asset_count") != 48 or len(actual_assets) != 48:
        errors.append(f"catalog.asset_count={len(actual_assets)} expected=48")
    expected_ids = {str(asset["asset_id"]) for asset in expected_assets}
    actual_ids = [str(asset.get("asset_id", "")) for asset in actual_assets if isinstance(asset, dict)]
    if len(set(actual_ids)) != len(actual_ids):
        errors.append("catalog.duplicate_id")
    if set(actual_ids) != expected_ids:
        errors.append("catalog.id_set_mismatch")
    for expected_asset in expected_assets:
        asset_id = str(expected_asset["asset_id"])
        actual = next((asset for asset in actual_assets if isinstance(asset, dict) and str(asset.get("asset_id", "")) == asset_id), None)
        if actual is None:
            errors.append(f"catalog.missing:{asset_id}")
            continue
        for field in (
            "display_name", "asset_type", "category", "object_class", "image", "thumbnail",
            "visible_bounds_px", "selection_bounds_px", "anchor_px", "footprint_tiles",
            "visual_footprint_tiles", "occupancy_footprint_tiles", "base_footprint_tiles",
            "collision_footprint_tiles", "collision_policy", "collision_profile_id",
            "navigation_policy", "placeable", "calibration_status", "geometry_pending_manual",
            "palette_path", "source_sha256", "source_bounds_px", "output_sha256", "processing",
        ):
            if actual.get(field) != expected_asset.get(field):
                errors.append(f"catalog.field_mismatch:{asset_id}:{field}")
        image_path = ROOT / str(expected_asset["image"])
        if not image_path.is_file():
            errors.append(f"image.missing:{image_path}")
        elif image_path.read_bytes() != outputs[str(expected_asset["image"])]:
            errors.append(f"image.bytes_mismatch:{image_path}")
    expected_paths = {ROOT / relative for relative in outputs}
    if OUTPUT_ROOT.is_dir():
        for path in OUTPUT_ROOT.glob("*.png"):
            if path not in expected_paths:
                errors.append(f"unexpected_output:{path}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    try:
        expected, outputs = build_expected()
        existing = read_json(CATALOG_PATH) if CATALOG_PATH.is_file() else None
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"SMALL_DECORATION_IMPORT_FAIL {exc}")
        return 1
    if args.check:
        if existing is None:
            print(f"SMALL_DECORATION_CHECK_FAIL missing_catalog={CATALOG_PATH}")
            return 1
        errors = validate_existing(existing, expected, outputs)
        if errors:
            print("SMALL_DECORATION_CHECK_FAIL")
            print("\n".join(errors))
            return 1
        print("SMALL_DECORATION_CHECK_PASS assets=48 grid=2x4 alpha_threshold=8 rgba_preserved=true")
        return 0

    if existing is not None and existing.get("package_id") not in (None, PACKAGE_ID):
        print("SMALL_DECORATION_IMPORT_REFUSE existing_catalog_not_owned_or_deterministic")
        return 1
    for image_rel, payload in outputs.items():
        path = ROOT / image_rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
    write_json(CATALOG_PATH, expected)
    print(f"SMALL_DECORATION_WRITE_PASS assets=48 output_dir={OUTPUT_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
