"""Build only the registered target-bar inner mask, preserving source artwork."""
import hashlib
import json
from collections import deque
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "assets/ui/gothic_hud/v2/target_bar_fill_mask.source.json"


def build():
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    source = ROOT / config["sourceTexture"]
    image = Image.open(source).convert("RGBA")
    assert list(image.size) == config["expectedSourceSize"]
    alpha = image.getchannel("A")
    seed = tuple(config["seed"])
    assert alpha.getpixel(seed) < config["alphaThresholdExclusive"]
    pending = deque([seed])
    interior = {seed}
    while pending:
        x, y = pending.popleft()
        assert 0 < x < image.width - 1 and 0 < y < image.height - 1, "Inner hole leaked to exterior"
        for point in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
            if point not in interior and alpha.getpixel(point) < config["alphaThresholdExclusive"]:
                interior.add(point)
                pending.append(point)
    left = min(x for x, y in interior)
    top = min(y for x, y in interior)
    right = max(x for x, y in interior) + 1
    bottom = max(y for x, y in interior) + 1
    bounds = [left, top, right - left, bottom - top]
    assert bounds == config["expectedInnerBounds"]
    mask = Image.new("RGBA", image.size)
    for point in interior:
        mask.putpixel(point, (255, 255, 255, 255))
    mask_path = ROOT / config["outputTexture"]
    mask.save(mask_path)
    source_sha = hashlib.sha256(source.read_bytes()).hexdigest()
    geometry = ROOT / config["outputGeometry"]
    geometry.parent.mkdir(parents=True, exist_ok=True)
    geometry.write_text(
        '# Generated by tools/build_hud_target_bar_mask.py; edit the source contract.\n'
        'extends RefCounted\n'
        f'const SOURCE_SHA256 := "{source_sha}"\n'
        f'const SOURCE_SIZE := Vector2({image.width}, {image.height})\n'
        f'const INNER_BOUNDS := Rect2i({left}, {top}, {right-left}, {bottom-top})\n'
        f'const INNER_PIXEL_COUNT := {len(interior)}\n', encoding="utf-8")
    print(f"HUD_TARGET_BAR_MASK_BUILD_PASS pixels={len(interior)} bounds={bounds} source_sha={source_sha}")


if __name__ == "__main__":
    build()
