"""Generate code-owned immutable catalogue data from an accepted real graph.

This is an internal framework code-entry lane, not a gameplay FeatureModule.
The generated file contains only serialized values, never target preloads.
"""
from __future__ import annotations
import argparse
import hashlib
import importlib.util
import json
import sys
from pathlib import Path


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--entry-id", required=True)
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--class-cache", type=Path, required=True)
    parser.add_argument("--max-source-nodes", type=int, required=True)
    parser.add_argument("--expected-producer-sha256", required=True)
    parser.add_argument("--plan", type=Path, required=True)
    parser.add_argument("--namespace", type=Path, required=True)
    parser.add_argument("--symbols", type=Path, required=True)
    parser.add_argument("--fold", type=Path, required=True)
    parser.add_argument("--expected-namespace-sha256", required=True)
    parser.add_argument("--expected-symbols-sha256", required=True)
    parser.add_argument("--expected-fold-sha256", required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    plan_raw = args.plan.read_bytes()
    plan = json.loads(plan_raw)
    if plan["status"] != "PASS" or plan["errors"] or plan["scope"] != "supported_gdscript_compile_inputs":
        raise ValueError("generated catalogue requires actual accepted subset graph")
    if not args.entry_id or len(args.entry_id) > 96 or any(c not in "abcdefghijklmnopqrstuvwxyz0123456789._" for c in args.entry_id):
        raise ValueError("internal entry identity syntax")
    artifacts = []
    evidence = {}
    engine = None
    for kind, path in (("namespace", args.namespace), ("global_symbols", args.symbols), ("constant_fold", args.fold)):
        raw = path.read_bytes()
        expected = {"namespace": args.expected_namespace_sha256, "global_symbols": args.expected_symbols_sha256, "constant_fold": args.expected_fold_sha256}[kind]
        if sha(raw) != expected:
            raise ValueError("approved native evidence byte mismatch: " + kind)
        value = json.loads(raw)
        evidence[kind] = value
        if engine is not None and value["engine"]["binary_sha256"] != engine["binary_sha256"]:
            raise ValueError("mixed native binary evidence")
        engine = value["engine"]
        artifacts.append({"kind": kind, "sha256": sha(raw), "producer_id": value["producer_id"],
                          "run_id": value["run_id"], "invocation_id": value["invocation_id"], "source_content_sha256": value["source_content_sha256"]})
    producer_path = Path(__file__).with_name("compile_code_preparation_inputs.py")
    if sha(producer_path.read_bytes()) != args.expected_producer_sha256:
        raise ValueError("reviewed producer bytes changed")
    spec = importlib.util.spec_from_file_location("internal_catalogue_verified_producer", producer_path)
    producer = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = producer
    spec.loader.exec_module(producer)
    actual = producer.compile_entry(args.root, plan["target_path"], args.class_cache, evidence["namespace"], engine["binary_sha256"], args.max_source_nodes, evidence["global_symbols"], evidence["constant_fold"])
    if actual != plan or actual["status"] != "PASS":
        raise ValueError("supplied graph differs from current strict producer; a JSON PASS grants no generation authority")
    bundle = {"schema_version": 1, "contract_id": "hc.internal_code_preparation.catalogue.candidate.v1", "runtime_mode": "pc_editor_text",
              "engine": engine, "producer_sha256": plan["source_fingerprints"]["producer"],
              "input_artifacts": artifacts, "entries": {args.entry_id: plan}, "plan_artifact_sha256": sha(plan_raw),
              "root_complete_preparation": "NOT_RUN", "android_exported_support": "MISSING"}
    encoded = json.dumps(bundle, ensure_ascii=False, separators=(",", ":"))
    if len(bundle["entries"]) != 1 or len(encoded.encode("utf-8")) > 65536:
        raise ValueError("first PC catalogue supports one bounded entry, at most 64KiB")
    if sum(record["bytes"] for record in plan["nodes"].values()) + sum(record["bytes"] for record in plan["source_fingerprints"]["source_context"].values()) > 524288:
        raise ValueError("first PC entry admission source/context exceeds 512KiB")
    executable = Path(engine["executable_path"])
    if not executable.is_file() or executable.stat().st_size > 268435456:
        raise ValueError("exact executing PC image is missing or exceeds 256MiB")
    source = 'extends RefCounted\n\n# Generated by build_internal_code_catalogue.py; never edit asset paths here.\n'
    source += 'const REGISTERED_TARGETS := ' + json.dumps({args.entry_id: plan["target_path"]}, ensure_ascii=False) + '\n'
    source += 'const PRODUCER_SHA256 := ' + json.dumps(bundle["producer_sha256"]) + '\n'
    source += 'const ENGINE_BINARY_SHA256 := ' + json.dumps(engine["binary_sha256"]) + '\n'
    source += 'const ENGINE_BINARY_BYTES := ' + str(executable.stat().st_size) + '\n'
    source += 'const BUNDLE_UTF8_BYTES := ' + str(len(encoded.encode("utf-8"))) + '\n'
    source += 'const BUNDLE_JSON := ' + json.dumps(encoded, ensure_ascii=False) + '\n\n'
    source += 'static func read_bundle() -> Dictionary:\n\tvar value: Variant = JSON.parse_string(BUNDLE_JSON)\n\treturn value if value is Dictionary else {}\n'
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(source, encoding="utf-8", newline="\n")
    print(json.dumps({"out": str(args.out), "sha256": sha(args.out.read_bytes()), "entry_id": args.entry_id,
                      "paths_from_graph": plan["prepared_inputs"], "native": "NOT_RUN", "production_publication": "NOT_RUN"}))


if __name__ == "__main__":
    main()
