"""Compile the primary server's naked-level ability procedure, fail on unknown syntax."""
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "dev_art_sources/reference/original_gameofmir/M2Server/ObjBase.pas"
SETUP = ROOT / "dev_art_sources/reference/original_gameofmir/MirServer/Mir200/!Setup.txt"
SHARE = ROOT / "dev_art_sources/reference/original_gameofmir/M2Server/M2Share.pas"
OUTPUT = ROOT / "scripts/generated/character_base_growth_v1.gd"
MANIFEST = ROOT / "assets/data/vanilla_176/character_base_growth_source_v1.json"
FIELDS = {"MaxHP": "max_hp", "MaxMP": "max_mp", "MaxWeight": "max_bag_weight",
          "MaxWearWeight": "max_wear_weight", "MaxHandWeight": "max_hand_weight"}
RANGES = {"DC": "attack", "MC": "magic", "SC": "tao", "AC": "defense", "MAC": "magic_defense"}


def build():
    source = SOURCE.read_text(encoding="gbk")
    setup = dict(re.findall(r"^(\w+)\s*=\s*([-\d.]+)\s*$", SETUP.read_text(encoding="gbk"), re.M))
    share = SHARE.read_text(encoding="gbk")
    procedure = source.split("procedure TBaseObject.RecalcLevelAbilitys();", 1)[1].split("procedure TBaseObject.HasLevelUp", 1)[0]
    hit = int(re.search(r"\bDEFHIT\s*=\s*(\d+)", share)[1])
    agility = int(re.search(r"\bDEFSPEED\s*=\s*(\d+)", share)[1])
    tao_agility = int(re.search(r"jTaos:\s*m_btSpeedPoint\s*:=\s*DEFSPEED\s*\+\s*m_BonusAbil.Speed div BonusTick.Speed\s*\+\s*(\d+)", source)[1])
    used_setup = {}

    def expression(value):
        value = value.replace("High(Word)", "65535")
        def parameter(match):
            key = match[1][0].upper() + match[1][1:]
            if key not in setup:
                raise ValueError("Missing primary Setup value " + key)
            used_setup[key] = setup[key]
            return setup[key]
        value = re.sub(r"g_Config.n(\w+)", parameter, value)
        value = re.sub(r"\b(nLevel|n)\s+div\s+(\d+)", lambda m: "int(%s / %s)" % ("level_value" if m[1] == "nLevel" else "step", m[2]), value)
        value = re.sub(r"\bnLevel\b", "level_value", value)
        value = re.sub(r"\bn\b", "step", value)
        value = value.replace("Round(", "source_round(").replace("_MIN(", "mini(").replace("_MAX(", "maxi(")
        if re.search(r"[^\d\s.+*/(),_a-z-]", value):
            raise ValueError("Untranslated expression " + value)
        return value

    lines = ["# Generated by tools/build_character_base_growth.py from the primary server.",
             "# Do not edit this derived file. Equipment and buffs are not inputs.", "extends RefCounted", "",
             "static func stats_for_level(profession: String, level: int) -> Dictionary:",
             "\tvar level_value := float(maxi(1, level))", "\tvar step := 0",
             '\tvar result := {"accuracy": %d, "agility": %d}' % (hit, agility), "\tmatch profession:"]
    for job, name in [("jTaos", "道士"), ("jWizard", "法师"), ("jWarr", "战士")]:
        block = re.search(r"\b" + job + r":\s*begin(.*?)\n\s*end;", procedure, re.S)[1]
        block = re.sub(r"//[^\n]*", "", block)
        lines.append('\t\t"%s":' % name)
        assigned = set()
        for lhs, rhs in re.findall(r"(m_Abil\.\w+|n)\s*:=\s*([^;]+);", block):
            if lhs == "n":
                lines.append("\t\t\tstep = " + expression(rhs.strip()))
                continue
            field = lhs.split(".")[1]
            assigned.add(field)
            if field in FIELDS:
                lines.append('\t\t\tresult["%s"] = %s' % (FIELDS[field], expression(rhs.strip())))
            elif field in RANGES:
                pair = ["0", "0"] if rhs.strip() == "0" else None
                if pair is None:
                    inner = re.fullmatch(r"MakeLong\((.*)\)", rhs.strip())[1]
                    depth = 0
                    for index, char in enumerate(inner):
                        depth += (char == "(") - (char == ")")
                        if char == "," and depth == 0:
                            pair = [inner[:index], inner[index + 1:]]
                            break
                for suffix, value in zip(["min", "max"], pair):
                    lines.append('\t\t\tresult["%s_%s"] = %s' % (RANGES[field], suffix, expression(value.strip())))
            else:
                raise ValueError("Unrecognized ability field " + field)
        assert assigned == FIELDS.keys() | RANGES.keys(), (job, assigned)
        if job == "jTaos":
            lines.append('\t\t\tresult["agility"] += %d' % tao_agility)
    lines += ["\t\t_:", '\t\t\tpush_error("Unknown profession for base growth: " + profession)', "\t\t\treturn {}", "\treturn result", "",
              "static func source_round(value: float) -> int:",
              "\t# Delphi Round uses nearest-even for an exact halfway value.",
              "\tvar lower := int(floor(value))", "\tvar fraction := value - float(lower)",
              "\tif absf(fraction - 0.5) < 0.000000001:",
              "\t\treturn lower if lower % 2 == 0 else lower + 1", "\treturn int(floor(value + 0.5))", ""]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    manifest = {"contract_id": "character.base_growth.primary.v1", "authority_lane": "server_rules",
                "distribution": "source.original_gameofmir.server_suite", "tier": "primary",
                "source_procedure": "TBaseObject.RecalcLevelAbilitys", "hit_procedure": "TBaseObject.RecalcHitSpeed",
                "sources": [{"path": p.relative_to(ROOT).as_posix(), "sha256": hashlib.sha256(p.read_bytes()).hexdigest()} for p in [SOURCE, SETUP, SHARE]],
                "setup_values": used_setup, "runtime": OUTPUT.relative_to(ROOT).as_posix(),
                "rounding": "Delphi nearest even", "lower_priority_sources_used": []}
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("CHARACTER_BASE_GROWTH_BUILD_PASS professions=3 attributes=17")


if __name__ == "__main__":
    build()
