extends "res://tests/hc_monster_ai/test_support.gd"
const Policy := preload("res://scripts/monster_ai_package/policy.gd")
const Warrior := preload("res://scripts/skills/warrior_melee_geometry.gd")

func _ready() -> void:
	check(Policy.valid(), "R00", "Frozen JSON/code policy pair loads")
	for index in range(8):
		var direction := Vector2.from_angle(TAU * float(index) / 8.0)
		check(Policy.within(Vector2.ZERO, direction * 1.499, Policy.START_GU), "R01a-%d" % index, "1.499 allowed")
		check(Policy.within(Vector2.ZERO, direction * 1.5, Policy.START_GU), "R01b-%d" % index, "1.5 allowed")
		check(not Policy.within(Vector2.ZERO, direction * 1.501, Policy.START_GU), "R01c-%d" % index, "1.501 denied")
	check(not Policy.within(Vector2.INF, Vector2.ZERO, 2.0), "R-invalid", "Invalid projection fails closed")
	check(Policy.within(Vector2.ZERO, Vector2(1.7,0), Policy.START_GU + Policy.DELAY_TOLERANCE_GU), "R05a", "Existing delayed impact tolerance")
	check(not Policy.within(Vector2.ZERO, Vector2(1.751,0),Policy.START_GU + Policy.DELAY_TOLERANCE_GU), "R05b", "Tolerance does not grow")
	check(Policy.should_close(1.8,1.5), "S02", "Cooldown approach continues")
	check(not Policy.should_close(1.5,1.5), "S03", "Stop in preferred band")
	check(is_equal_approx(Policy.preferred(1.189),1.5), "S-pref", "Contact does not replace preferred distance")
	check(is_equal_approx(Policy.preferred(1.6),1.6), "S08", "Do not compress a large physical body")
	check(Policy.frontline_blocks(Vector2(2,0),Vector2.ZERO,Vector2(1,0),.35,.398,.35,2,1),"O01","Front body blocks rear")
	check(not Policy.frontline_blocks(Vector2(1,0),Vector2.ZERO,Vector2(2,0),.35,.398,.35,1,2),"O02","Rear does not block front")
	check(not Policy.frontline_blocks(Vector2(2,0),Vector2.ZERO,Vector2(-1,0),.35,.398,.35,2,1),"O03","Behind target does not block")
	check(not Policy.frontline_blocks(Vector2(2,0),Vector2.ZERO,Vector2(1,2),.35,.398,.35,2,1),"O-side","Off-path actor does not block")
	check(Policy.frontline_blocks(Vector2(2,0),Vector2.ZERO,Vector2(1,.60),.35,.398,.70,2,1),"O04","Large footprint is not a point")
	check(Policy.frontline_blocks(Vector2(2,0),Vector2.ZERO,Vector2(2,0),.35,.398,.35,2,1),"O09a","Stable overlap order blocks rear rank")
	check(not Policy.frontline_blocks(Vector2(2,0),Vector2.ZERO,Vector2(2,0),.35,.398,.35,1,2),"O09b","Stable overlap order keeps a front attacker")
	check(Policy.core_crossed(Vector2(-1,0),Vector2(1,0),Vector2.ZERO,.35,.35),"O-core1","Cannot walk through a body")
	check(Policy.core_crossed(Vector2(-.4,0),Vector2(.9,0),Vector2.ZERO,.35,.35),"O-core2","Existing overlap cannot cross centre")
	check(not Policy.core_crossed(Vector2(-.4,0),Vector2(-.9,0),Vector2.ZERO,.35,.35),"O-core3","Existing overlap can separate")
	var ordinary_radius := 16.0 / (32.0 * sqrt(2.0))
	var boss_radius := 28.0 / (32.0 * sqrt(2.0))
	check(Warrior.thrust_footprint_slot_for_direction_ground_gu(Vector2.ZERO,Vector2(2,0),ordinary_radius,Vector2.RIGHT)==2,"S04-red-model","A parked 2-GU small body is in thrust slot2")
	check(Warrior.thrust_footprint_slot_for_direction_ground_gu(Vector2.ZERO,Vector2(1.5,0),ordinary_radius,Vector2.RIGHT)==1,"S04-green-model","Preferred position intersects first segment")
	check(Warrior.thrust_footprint_slot_for_direction_ground_gu(Vector2.ZERO,Vector2(2.5,0),ordinary_radius,Vector2.RIGHT)==2,"S05","Player-earned spacing retains slot2")
	check(Warrior.thrust_footprint_slot_for_direction_ground_gu(Vector2.ZERO,Vector2(2,0),boss_radius,Vector2.RIGHT)==1,"S07","Primary footprint wins for large body")
	finish("geometry")
