"use strict";
let SIZE=700,MAP_W=700,MAP_H=700,VIEW_ZOOM=.5,CAMERA_X=0,CAMERA_Y=0,HOVER_GRID=null;const BLOCKED=128,VIEW_W=1400,VIEW_H=900,HALF_W=32,HALF_H=16;
const layerDefs=["base_ground","transition","road","ground_decoration","building_base","obstacle","foreground","npc","spawn","logic"];
const terrainTypes=[[0,"草地","#52683b"],[1,"深草地","#344b2d"],[2,"疏林地","#263f28"],[3,"泥土地","#756044"],[4,"城郊硬地","#736d5d"],[5,"土路","#96734d"],[6,"石路","#77766e"],[7,"水域","#294f62"],[BLOCKED,"禁行区","#c3312b"],[256,"恢复通行","#d9d3b4"]];
const catalogs={
 npc:["比奇杂货商","比奇武器店","书店老板","武馆教头","比奇老兵","仓库管理员","药店老板","任务发布人","守卫"],
 monster:["稻草人","多钩猫","钉耙猫","半兽人","森林雪人","食人花","多钩猫王","钉耙猫王","骷髅","骷髅战士","骷髅精灵","尸王"],
 portal:["天然洞穴入口","兽人古墓入口","比奇废矿入口","沃玛森林入口","毒蛇山谷入口","城门","自定义出口"],spawn_point:["默认出生点","复活点"],area:["安全区","城镇区","野外区","怪物区","任务触发区","音乐区","天气区","禁战区","禁刷区"],
 decor:`bich_camp_border_barricade_01 bich_camp_border_direction_sign_01 bich_camp_border_fence_corner_01 bich_camp_border_fence_straight_01 bich_camp_border_fence_straight_02 bich_camp_border_flag_01 bich_camp_border_flag_02 bich_camp_border_flag_03 bich_camp_border_gate_left_01 bich_camp_border_gate_right_01 bich_camp_border_guard_brazier_01 bich_camp_center_campfire_01 bich_camp_center_campfire_ground_01 bich_camp_center_log_bench_01 bich_camp_center_log_bench_02 bich_camp_center_signpost_01 bich_camp_center_supplies_01 bich_camp_common_tent_01 bich_camp_common_tent_02 bich_camp_forge_anvil_01 bich_camp_forge_armor_stand_01 bich_camp_forge_coal_01 bich_camp_forge_furnace_01 bich_camp_forge_shelter_01 bich_camp_forge_shield_rack_01 bich_camp_forge_tool_rack_01 bich_camp_forge_weapon_rack_01 bich_camp_forge_weapon_rack_02 bich_camp_forge_workbench_01 bich_camp_ground_dirt_01 bich_camp_ground_dirt_02 bich_camp_ground_grass_01 bich_camp_ground_grass_02 bich_camp_ground_road_01 bich_camp_ground_road_02 bich_camp_ground_stone_01 bich_camp_ground_stone_02 bich_camp_healer_herb_basket_01 bich_camp_healer_herb_basket_02 bich_camp_healer_herb_rack_01 bich_camp_healer_medicine_box_01 bich_camp_healer_tent_01 bich_camp_healer_worktable_01 bich_camp_light_brazier_01 bich_camp_light_campfire_01 bich_camp_light_furnace_01 bich_camp_light_lamp_01 bich_camp_light_lamp_object_01 bich_camp_misc_bucket_01 bich_camp_misc_cloth_01 bich_camp_misc_firewood_01 bich_camp_misc_rope_01 bich_camp_misc_stool_01 bich_camp_misc_toolbox_01 bich_camp_misc_training_dummy_01 bich_camp_misc_water_trough_01 bich_camp_scroll_bookshelf_01 bich_camp_scroll_books_01 bich_camp_scroll_chest_01 bich_camp_scroll_lamp_01 bich_camp_scroll_tent_01 bich_camp_scroll_worktable_01 bich_camp_stash_barrel_01 bich_camp_stash_barrel_02 bich_camp_stash_cart_01 bich_camp_stash_chest_01 bich_camp_stash_crate_01 bich_camp_stash_crate_02 bich_camp_stash_sack_01 bich_camp_stash_sack_02 bich_camp_stash_shelf_01 bich_camp_stash_tent_01`.split(" ")
};
const canvas=document.querySelector("#map"),ctx=canvas.getContext("2d",{alpha:false});let cells=new Uint8Array(SIZE*SIZE);const colors=terrainTypes.slice(0,8).map(x=>x[2]);
let mode="terrain",tool=0,painting=false,last=null,entities=[],selected=-1,dragging=false,undo=[],redo=[],assetCatalog=[],selectedAsset=null;const imageCache={};
const palette=document.querySelector("#palette"),brush=document.querySelector("#brush"),status=document.querySelector("#status"),entityType=document.querySelector("#entityType"),entityName=document.querySelector("#entityName");
const layerSelect=document.querySelector("#layerSelect");for(const id of layerDefs){const o=document.createElement("option");o.value=o.textContent=id;layerSelect.appendChild(o)}
async function loadAssets(){try{const response=await fetch('/assets/data/map_editor/asset_catalog.json');const data=await response.json();assetCatalog=data.objects||[];renderAssetGrid()}catch(e){document.querySelector('#selectedAsset').textContent='素材库读取失败：'+e.message}}
function renderAssetGrid(){const q=document.querySelector('#assetSearch').value.toLowerCase(),filter=document.querySelector('#assetFilter').value,grid=document.querySelector('#assetGrid');grid.innerHTML='';for(const a of assetCatalog.filter(a=>(!q||(a.name+' '+a.category).toLowerCase().includes(q))&&(filter==='all'||(filter==='ground')===(a.layer==='base_ground'))).slice(0,500)){const b=document.createElement('button');b.className='asset-card'+(selectedAsset?.id===a.id?' active':'');b.title=`${a.name}\n${a.width}×${a.height}\n${a.layer}`;const thumb=document.createElement('canvas');thumb.width=96;thumb.height=58;const label=document.createElement('span');label.textContent=a.name;b.append(thumb,label);const img=new Image();img.onload=()=>{const r=a.region||{x:0,y:0,width:img.width,height:img.height},s=Math.min(90/r.width,54/r.height);thumb.getContext('2d').drawImage(img,r.x,r.y,r.width,r.height,(96-r.width*s)/2,(58-r.height*s)/2,r.width*s,r.height*s)};img.src='/'+a.image;b.onclick=()=>{selectedAsset=a;layerSelect.value=a.layer||'obstacle';setMode('asset');document.querySelector('#selectedAsset').textContent=`已选：${a.name}｜${a.width}×${a.height}｜${a.layer}`;renderAssetGrid()};grid.appendChild(b)}}
document.querySelector('#assetSearch').oninput=renderAssetGrid;document.querySelector('#assetFilter').onchange=renderAssetGrid;loadAssets();
for(const [id,name,color] of terrainTypes){const b=document.createElement("button");b.className="tool";b.innerHTML=`<i class="swatch" style="background:${color}"></i>${name}`;b.onclick=()=>{tool=id;document.querySelectorAll(".tool").forEach(x=>x.classList.remove("active"));b.classList.add("active")};palette.appendChild(b)}palette.firstChild.classList.add("active");
function setMode(value){mode=value;document.querySelectorAll("#modes button").forEach(b=>b.classList.toggle("active",b.dataset.mode===value));document.querySelector("#terrainPanel").hidden=value!=="terrain";document.querySelector("#entityPanel").hidden=value!=="entity";if(value!=="select"){selected=-1;showProperties()}render()}
document.querySelectorAll("#modes button").forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
function fillCatalog(){entityName.innerHTML="";for(const name of catalogs[entityType.value]){const o=document.createElement("option");o.value=o.textContent=name;entityName.appendChild(o)}}entityType.onchange=fillCatalog;fillCatalog();
canvas.width=VIEW_W;canvas.height=VIEW_H;brush.oninput=()=>document.querySelector("#brushValue").textContent=brush.value;document.querySelector("#zoom").oninput=e=>{VIEW_ZOOM=+e.target.value/100;document.querySelector("#zoomValue").textContent=e.target.value+"%";render()};
document.querySelector('#panUp').onclick=()=>{CAMERA_Y+=180;render()};document.querySelector('#panDown').onclick=()=>{CAMERA_Y-=180;render()};document.querySelector('#panLeft').onclick=()=>{CAMERA_X+=240;render()};document.querySelector('#panRight').onclick=()=>{CAMERA_X-=240;render()};
function state(){return {cells:cells.slice(),entities:structuredClone(entities)}}function snapshot(){undo.push(state());if(undo.length>20)undo.shift();redo=[]}function restore(s){cells.set(s.cells);entities=structuredClone(s.entities);selected=-1;showProperties();render()}
function gridToScreen(x,y){return [(x-y)*HALF_W*VIEW_ZOOM+VIEW_W/2+CAMERA_X,(x+y-(MAP_W+MAP_H)/2)*HALF_H*VIEW_ZOOM+VIEW_H/2+CAMERA_Y]}
function screenToGrid(sx,sy){const wx=(sx-VIEW_W/2-CAMERA_X)/VIEW_ZOOM,wy=(sy-VIEW_H/2-CAMERA_Y)/VIEW_ZOOM+(MAP_W+MAP_H)/2*HALF_H;return [(wx/HALF_W+wy/HALF_H)/2,(wy/HALF_H-wx/HALF_W)/2]}
function point(e){const r=canvas.getBoundingClientRect(),sx=(e.clientX-r.left)*VIEW_W/r.width,sy=(e.clientY-r.top)*VIEW_H/r.height,snap=document.querySelector('#snapEnabled').checked?+document.querySelector('#snapSize').value:.01,g=screenToGrid(sx,sy);return [Math.max(0,Math.min(MAP_W-1,Math.round(g[0]/snap)*snap)),Math.max(0,Math.min(MAP_H-1,Math.round(g[1]/snap)*snap))]}
function stamp(x,y,id){const radius=+brush.value/2;for(let yy=Math.max(0,Math.floor(y-radius));yy<Math.min(MAP_H,Math.ceil(y+radius));yy++)for(let xx=Math.max(0,Math.floor(x-radius));xx<Math.min(MAP_W,Math.ceil(x+radius));xx++){if((xx-x)**2+(yy-y)**2>radius**2)continue;const i=yy*SIZE+xx;if(id===BLOCKED)cells[i]|=BLOCKED;else if(id===256)cells[i]&=127;else cells[i]=(cells[i]&BLOCKED)|id}}
function line(a,b,id){const d=Math.max(Math.abs(b[0]-a[0]),Math.abs(b[1]-a[1]),1);for(let i=0;i<=d;i++)stamp(Math.round(a[0]+(b[0]-a[0])*i/d),Math.round(a[1]+(b[1]-a[1])*i/d),id)}
function nearest(p){let best=-1,dist=Math.max(1.5,24/(HALF_W*VIEW_ZOOM));entities.forEach((e,i)=>{const d=Math.hypot(e.x-p[0],e.y-p[1]);if(d<dist){dist=d;best=i}});return best}
canvas.onpointerdown=e=>{e.preventDefault();const p=point(e);if(p[0]>=MAP_W||p[1]>=MAP_H)return;snapshot();if(mode==="terrain"){painting=true;last=p;line(p,p,e.button===2?0:tool)}else if(mode==="asset"&&selectedAsset){entities.push({instanceId:crypto.randomUUID(),type:'asset',name:selectedAsset.name,templateId:selectedAsset.id,image:selectedAsset.image,region:selectedAsset.region||null,layer:layerSelect.value,x:p[0],y:p[1],pivot:selectedAsset.pivot,collision:!!selectedAsset.blockMove,occlusion:!!selectedAsset.occlusion});selected=entities.length-1;showProperties()}else if(mode==="entity"){const type=entityType.value;entities.push({instanceId:crypto.randomUUID(),type,name:entityName.value,layer:layerSelect.value,x:p[0],y:p[1],count:type==="monster"?4:1,radius:type==="monster"?12:(type==="area"?30:0),respawnSeconds:type==="monster"?60:0,collision:type==="decor",targetMapId:""});selected=entities.length-1;showProperties()}else{selected=nearest(p);dragging=selected>=0;showProperties()}render()};
canvas.onpointermove=e=>{const p=point(e);HOVER_GRID=p;status.textContent=`吸附格坐标 ${p[0]}, ${p[1]}　对象 ${entities.length}`;if(painting){line(last,p,(e.buttons&2)?0:tool);last=p}else if(dragging&&selected>=0){entities[selected].x=p[0];entities[selected].y=p[1];showProperties()}render()};canvas.onpointerleave=()=>{HOVER_GRID=null;render()};window.onpointerup=()=>{painting=false;dragging=false;last=null};canvas.oncontextmenu=e=>e.preventDefault();
function drawSnapDiamond(g,color){const points=[[g[0]-.5,g[1]-.5],[g[0]+.5,g[1]-.5],[g[0]+.5,g[1]+.5],[g[0]-.5,g[1]+.5]].map(p=>gridToScreen(...p));ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(...points[0]);for(const p of points.slice(1))ctx.lineTo(...p);ctx.closePath();ctx.stroke()}
function render(){ctx.fillStyle='#090b08';ctx.fillRect(0,0,VIEW_W,VIEW_H);const corners=[[0,0],[MAP_W,0],[MAP_W,MAP_H],[0,MAP_H]].map(p=>gridToScreen(...p));ctx.fillStyle='#34432c';ctx.beginPath();ctx.moveTo(...corners[0]);for(const p of corners.slice(1))ctx.lineTo(...p);ctx.closePath();ctx.fill();if(document.querySelector('#grid').checked){let step=+document.querySelector('#snapSize').value;while(HALF_W*VIEW_ZOOM*step<5)step*=2;for(let x=0;x<=MAP_W;x+=step){const a=gridToScreen(x,0),b=gridToScreen(x,MAP_H),major=Math.abs(x%(step*4))<.001;ctx.strokeStyle=major?'#ffe69a88':'#ffffff38';ctx.lineWidth=major?1.2:.6;ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}for(let y=0;y<=MAP_H;y+=step){const a=gridToScreen(0,y),b=gridToScreen(MAP_W,y),major=Math.abs(y%(step*4))<.001;ctx.strokeStyle=major?'#ffe69a88':'#ffffff38';ctx.lineWidth=major?1.2:.6;ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}}entities.slice().sort((a,b)=>(a.x+a.y)-(b.x+b.y)).forEach(e=>{const p=gridToScreen(e.x,e.y);ctx.save();ctx.translate(p[0]-e.x,p[1]-e.y);const text=ctx.fillText;ctx.fillText=()=>{};drawEntity(e,entities.indexOf(e));ctx.fillText=text;ctx.restore()});if(HOVER_GRID)drawSnapDiamond(HOVER_GRID,'#55eaff');if(selected>=0)drawSnapDiamond([entities[selected].x,entities[selected].y],'#fff200');status.textContent=`等距格坐标｜对象 ${entities.length}｜缩放 ${Math.round(VIEW_ZOOM*100)}%｜吸附 ${document.querySelector('#snapSize').selectedOptions[0].text}`}
function drawEntity(e,i){ctx.save();if(e.type==="monster"){ctx.fillStyle="#d14d43aa";ctx.beginPath();ctx.arc(e.x,e.y,Math.max(5,e.radius),0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.fillText(`${e.name}×${e.count}`,e.x+7,e.y-6)}else if(e.type==="npc"){ctx.fillStyle="#ffd05a";ctx.fillRect(e.x-5,e.y-5,10,10);ctx.fillStyle="#fff";ctx.fillText(e.name,e.x+7,e.y-6)}else if(e.type==="portal"){ctx.strokeStyle="#61d9ff";ctx.lineWidth=3;ctx.strokeRect(e.x-8,e.y-8,16,16);ctx.fillStyle="#dff8ff";ctx.fillText(e.name,e.x+10,e.y-6)}else if(e.type==="area"){ctx.fillStyle="#39d87944";ctx.fillRect(e.x-e.radius,e.y-e.radius,e.radius*2,e.radius*2);ctx.strokeStyle="#63ff9a";ctx.strokeRect(e.x-e.radius,e.y-e.radius,e.radius*2,e.radius*2);ctx.fillStyle="#fff";ctx.fillText(e.name,e.x+5,e.y)}else if(e.type==="spawn_point"){ctx.fillStyle="#fff";ctx.beginPath();ctx.moveTo(e.x,e.y-10);ctx.lineTo(e.x+9,e.y+8);ctx.lineTo(e.x-9,e.y+8);ctx.fill()}else{drawDecor(e);ctx.fillStyle="#ddd";ctx.fillText(e.name.replace("bich_camp_",""),e.x+10,e.y-6)}if(i===selected){ctx.strokeStyle="#fff200";ctx.lineWidth=2;ctx.strokeRect(e.x-12,e.y-12,24,24)}ctx.restore()}
function drawDecor(e){const path=e.image?'/'+e.image:`/assets/presentation/skins/gothic_bich_camp/sprites/${e.name}.png`;let img=imageCache[path];if(!img){img=new Image();img.src=path;img.onload=render;imageCache[path]=img}if(img.complete&&img.naturalWidth){const region=e.region||{x:0,y:0,width:img.width,height:img.height},base=VIEW_ZOOM;ctx.save();ctx.translate(e.x,e.y);ctx.rotate((e.rotation||0)*Math.PI/180);ctx.scale(e.scaleX??1,e.scaleY??1);ctx.drawImage(img,region.x,region.y,region.width,region.height,-region.width*base/2,-region.height*base,region.width*base,region.height*base);ctx.restore()}else{ctx.fillStyle="#b89773";ctx.fillRect(e.x-5,e.y-5,10,10)}}
function hex(s){return [parseInt(s.slice(1,3),16),parseInt(s.slice(3,5),16),parseInt(s.slice(5,7),16)]}
function showProperties(){const box=document.querySelector("#properties");box.hidden=selected<0;if(selected<0)return;const e=entities[selected];document.querySelector("#propName").value=e.name;document.querySelector("#propX").value=e.x;document.querySelector("#propY").value=e.y;document.querySelector("#propRotation").value=e.rotation||0;document.querySelector("#propScaleX").value=e.scaleX??1;document.querySelector("#propScaleY").value=e.scaleY??1;document.querySelector("#propCount").value=e.count||1;document.querySelector("#propRadius").value=e.radius||0;document.querySelector("#propRespawn").value=e.respawnSeconds||0;document.querySelector("#propCollision").checked=!!e.collision;document.querySelector("#monsterProps").hidden=e.type!=="monster";document.querySelector('#portalTargetRow').hidden=e.type!=="portal";document.querySelector('#portalArrivalRow').hidden=e.type!=="portal";document.querySelector('#propTargetMap').value=e.targetMapId||'';document.querySelector('#propArrivalX').value=e.arrivalX||0;document.querySelector('#propArrivalY').value=e.arrivalY||0}
for(const [id,key,number] of [["propName","name",false],["propX","x",true],["propY","y",true],["propRotation","rotation",true],["propScaleX","scaleX",true],["propScaleY","scaleY",true],["propCount","count",true],["propRadius","radius",true],["propRespawn","respawnSeconds",true],["propTargetMap","targetMapId",false],["propArrivalX","arrivalX",true],["propArrivalY","arrivalY",true]])document.querySelector("#"+id).oninput=ev=>{if(selected<0)return;entities[selected][key]=number?+ev.target.value:ev.target.value;render()};document.querySelector("#propCollision").onchange=e=>{if(selected>=0)entities[selected].collision=e.target.checked};
function deleteSelected(){if(selected<0)return;snapshot();entities.splice(selected,1);selected=-1;showProperties();render()}document.querySelector("#deleteEntity").onclick=deleteSelected;window.onkeydown=e=>{if(e.key==="Delete")deleteSelected()};document.querySelector("#grid").onchange=render;document.querySelector("#snapSize").onchange=render;
document.querySelector("#undo").onclick=()=>{if(!undo.length)return;redo.push(state());restore(undo.pop())};document.querySelector("#redo").onclick=()=>{if(!redo.length)return;undo.push(state());restore(redo.pop())};
function activeCells(){const a=[];for(let y=0;y<MAP_H;y++)for(let x=0;x<MAP_W;x++)a.push(cells[y*SIZE+x]);return a}function rle(source=activeCells()){const out=[];let v=source[0]||0,n=1;for(let i=1;i<source.length;i++){if(source[i]===v&&n<65535)n++;else{out.push([v,n]);v=source[i];n=1}}out.push([v,n]);return out}function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function project(){const layerData=Object.fromEntries(layerDefs.map(x=>[x,entities.filter(e=>e.layer===x)]));return {schemaVersion:1,mapId:document.querySelector('#mapId').value,mapName:document.querySelector('#mapName').value,size:{width:MAP_W,height:MAP_H},grid:{tileWidth:64,tileHeight:32,type:'isometric'},layers:layerData,terrain:{encoding:'rle_u8',blockedBit:BLOCKED,runs:rle()},objects:entities.filter(e=>e.type==='decor'||e.type==='asset'),npcs:entities.filter(e=>e.type==='npc'),spawns:entities.filter(e=>e.type==='monster'),areas:entities.filter(e=>e.type==='area'),portals:entities.filter(e=>e.type==='portal'),spawnPoints:entities.filter(e=>e.type==='spawn_point')}}
document.querySelector("#save").onclick=()=>download(new Blob([JSON.stringify(project(),null,2)],{type:"application/json"}),document.querySelector('#mapId').value+"_project.json");
const file=document.querySelector("#file");document.querySelector("#load").onclick=()=>file.click();file.onchange=async()=>{try{const d=JSON.parse(await file.files[0].text()),w=d.size?.width||d.width,h=d.size?.height||d.height,runs=d.terrain?.runs||d.runs;if(!w||!h||!Array.isArray(runs))throw Error("尺寸或格式不正确");resetMap(w,h,0);let p=0;for(const [v,n] of runs)for(let k=0;k<n;k++){const y=Math.floor(p/w),x=p%w;cells[y*SIZE+x]=v;p++}entities=d.entities||[...(d.objects||[]),...(d.npcs||[]),...(d.spawns||[]),...(d.areas||[]),...(d.portals||[]),...(d.spawnPoints||[])];document.querySelector('#mapId').value=d.mapId||'new_map';document.querySelector('#mapName').value=d.mapName||'新地图';render()}catch(e){status.textContent="导入失败："+e.message}file.value=""};
function resetMap(w,h,t){MAP_W=w;MAP_H=h;SIZE=Math.max(w,h);canvas.width=VIEW_W;canvas.height=VIEW_H;cells=new Uint8Array(SIZE*SIZE);for(let y=0;y<h;y++)for(let x=0;x<w;x++)cells[y*SIZE+x]=t;entities=[];undo=[];redo=[];CAMERA_X=0;CAMERA_Y=0;render()}
document.querySelector('#newMap').onclick=()=>resetMap(+document.querySelector('#mapWidth').value,+document.querySelector('#mapHeight').value,+document.querySelector('#defaultTerrain').value);
function validateMap(){const p=project(),issues=[];if(!p.mapId)issues.push('错误：缺少地图ID');if(!p.spawnPoints.length)issues.push('错误：缺少玩家出生点');const ids=new Set;for(const e of entities){if(ids.has(e.instanceId))issues.push('错误：对象ID重复 '+e.instanceId);ids.add(e.instanceId);if(e.x>=MAP_W||e.y>=MAP_H)issues.push('错误：对象越界 '+e.name);if(e.type==='monster'&&(cells[Math.floor(e.y)*SIZE+Math.floor(e.x)]&BLOCKED))issues.push('错误：刷怪点位于阻挡区 '+e.name);if(e.type==='portal'&&!e.targetMapId)issues.push('警告：传送点未设置目标 '+e.name)}if(!p.portals.length)issues.push('警告：地图没有传送点');return issues}
document.querySelector('#validate').onclick=()=>{const e=validateMap();status.textContent=e.length?e.join('\n'):'地图检查通过：可以导出'};
document.querySelector('#exportGame').onclick=()=>{const errors=validateMap().filter(x=>x.startsWith('错误'));if(errors.length){status.textContent=errors.join('\n');return}const p=project(),id=p.mapId;download(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),id+'_map.json');download(new Blob([JSON.stringify({width:MAP_W,height:MAP_H,encoding:'rle_u8',runs:rle()},null,2)],{type:'application/json'}),id+'_collision.json');download(new Blob([JSON.stringify({width:MAP_W,height:MAP_H,source:'collision',walkableCodes:[0,3,4]},null,2)],{type:'application/json'}),id+'_nav.json')};
document.querySelector("#preview").onclick=()=>canvas.toBlob(b=>download(b,document.querySelector('#mapId').value+"_preview.png"));document.querySelector("#clear").onclick=()=>{if(confirm("确定清空地形和所有对象？"))resetMap(MAP_W,MAP_H,0)};render();
